### ISSUE TITLE
Stan program prints not getting through to console 

### ISSUE THREAD

**Issue by breckbaldwin** [stan-dev/cmdstanpy#149] opened 2019-10-22 15:12 UTC
#### Summary:
Could use print statements for Stan debugging but the below Stan print statements do not make it to the console. 

#### Description:

Code: 
```
import os
from cmdstanpy import cmdstan_path, CmdStanModel

model_code = """transformed data {
  print("Hello from transformed data");
}

parameters {
  real<lower=0,upper=1> theta3;
} 
model {
  print("hi from the model block");
}
"""

path='/tmp/foo.stan'

with open(path, 'w') as f:
  f.write(model_code)


hello_model = CmdStanModel(stan_file=path)
hello_model.compile()

fit = hello_model.sample(csv_basename='./hello')
```

#### Additional Information:
None

#### Current Version:
cmdstanpy, 0.5.0, cmdstan 2.20.0 , OSX 10.13.6

**Comment by mitzimorris** [comment] 2019-10-24 14:10
this is not a bug.  prints to console are available in the console files.
printing the StanMCMC object reports the location of the console files.

**Comment by mitzimorris** [comment] 2019-10-24 15:17
larger issue here is how to handle console output - always putting it to a file by default is good for production but bad for debug.

**Comment by mitzimorris** [comment] 2020-02-25 23:34
larger issue is #152, closing this

**Closed by mitzimorris** 2020-02-25 23:34 UTC
