### ISSUE TITLE
Best way to use MPI with cmdstanpy

### ISSUE THREAD

**Issue by grburgess** [stan-dev/cmdstanpy#274] opened 2020-08-11 16:12 UTC
#### Summary:

What is the proper workflow for running a python script when one wants to use the MPI threading for reduce_sum

#### Description:

I have a python script which will pass some data to a stan model.

```python

import cmdstanpy 

model = cmdstanpy.CmdStanModel( stan_file=stan_file, cpp_options={"STAN_MPI: TRUE"}

n_chains = 4
n_procs = 12

model.sample(..., parallel_chains = n_chains, threads_per_chain=n_procs)

```
Do I run this with 

```bash
mpirun -np 48 python my script.py
```
? So far, this is all crashing locally although all the mpi checks in Stan-math pass.

#### Current Version:
CmdStan = 2.24
CmdStanPy = 0.9.5

**Comment by mitzimorris** [comment] 2020-08-11 16:27
please update to latest CmdStanPy - 9.63 is up on PyPi.
documentation is here:
https://cmdstanpy.readthedocs.io/en/latest/sample.html#example-high-level-parallelization-with-reduce-sum

**Comment by grburgess** [comment] 2020-08-11 16:29
Thanks, so STAN_THREADS works completely fine. it is the STAN_MPI part that is not working as expected.

**Comment by mitzimorris** [comment] 2020-08-11 16:30
are you using latest CmdStanPy?

**Comment by mitzimorris** [comment] 2020-08-11 16:44
OK, I think the problem is that `mpirun` isn't what you want here - if I understand the open-mpi docs: https://www.open-mpi.org/doc/v4.0/man1/mpirun.1.php

> % mpirun [ -np X ] [ --hostfile <filename> ] <program>
> This will run X copies of <program> in your current run-time environment (if running under a supported resource manager, Open MPI’s mpirun will usually automatically use the corresponding resource manager process starter, as opposed to, for example, rsh or ssh, which require the use of a hostfile, or will default to running all X copies on the localhost), scheduling (by default) in a round-robin fashion by CPU slot. See the rest of this page for more details.
> 

you don't want to run 48 copies of this script - what you want is to run this on a cluster node which has 48 cores.
checking with @rok-cesnovar - is this correct?

**Comment by grburgess** [comment] 2020-08-11 16:47
currently, yes, I want to run this on 48 cores of a single node. I'm doing some speed tests between MPI and threads as I saw in the Stan forums that MPI is currently 20% faster. Also, if I need to spread the computation across nodes, I will need to use MPI. 

Additionally, when I figure this workflow out, I would like to document it and do a PR on the docs here.

**Comment by grburgess** [comment] 2020-08-11 16:48
TBH, there is not a lot of documentation on Stan + MPI in general.

**Comment by ahartikainen** [comment] 2020-08-11 16:59
Hi, I think you need to define `STAN_MPI` (`os.environ`?) and then setup compiler manually

See

    model._cmds

And add the needed bits for mpi

**Comment by mitzimorris** [comment] 2020-08-11 17:11
> Additionally, when I figure this workflow out, I would like to document it and do a PR on the docs here.

that would be awesome. 

> See
>   `model._cmds`
> And add the needed bits for mpi

@ahartikainen - don't quite understand the above.

**Comment by mitzimorris** [comment] 2020-08-11 17:18
> TBH, there is not a lot of documentation on Stan + MPI in general.

you're correct - for CmdStan, added this page to the CmdStan User's Guide:  https://mc-stan.org/docs/2_24/cmdstan-guide/parallelization.html
if there's more config required, then we need to know - issues and PRs go on the https://github.com/stan-dev/docs repo

**Comment by ahartikainen** [comment] 2020-08-11 17:31
I miss the old threading / mpi wikipage. Is it still somewhere?

**Comment by mitzimorris** [comment] 2020-08-11 17:57
you have to hack the wiki to find a good hashtag for a point in history when that page existed - is this what you're looking for?

https://github.com/stan-dev/math/wiki/MPI-parallelism/7ec082d6c6d8524606f9de50ccb6ebe7c6664dc4

**Comment by ahartikainen** [comment] 2020-08-11 18:06
Yes,

so basically I just read that and it needs a bit more work from the user

Install MPI
set-up `make/local`
rebuilt cmdstan (e.g. should we have a different cmdstan folder for MPI)
build executable
--> mpirun -np N executable

**Comment by mitzimorris** [comment] 2020-08-11 18:10
> rebuilt cmdstan (e.g. should we have a different cmdstan folder for MPI)

so script in issue description needs to add:

```
cmdstanpy.set_cmdstan_path('path/to/cmdstan/mpi')
```

**Comment by ahartikainen** [comment] 2020-08-11 18:12
basically yes, a user given folder with mpi ready cmdstan.

**Comment by rok-cesnovar** [comment] 2020-08-11 18:30
mpirun only works with executables, not python scripts. So cmdstanpy/r will not work with that right now. 

See https://github.com/stan-dev/cmdstanr/issues/117 for more discussion on that and an example on how it could be used by Yi.

> currently, yes, I want to run this on 48 cores of a single node. I'm doing some speed tests between MPI and threads as I saw in the Stan forums that MPI is currently 20% faster

This was probably an old thread (more than a year ago I assume). STAN_THREADS on a single machine are faster or comparable to MPI. Also reduce_sum only works on STAN_THREADS. MPI backend is currently map_rect only.

**Comment by grburgess** [comment] 2020-08-11 18:50
well that's an important bit of information. Ok, i've used mpirun on python scripts before and it was fine. 

Anyhow, perhaps it would be useful (i would like to help) to collect all this info some where?

**Comment by mitzimorris** [comment] 2020-08-11 22:54
yes, it would be very useful - the docs repo - https://github.com/stan-dev/docs
has the CmdStan User's Guide R markdown source code - 
this is the page I referenced above:
https://github.com/stan-dev/docs/blob/master/src/cmdstan-guide/parallelization.Rmd

if you want to file an issue and then edit the Rmd file and submit a PR I can help check
that the whole thing renders properly - getting the docs toolchain -
pandoc, and R packages knitr, gitbook is a PITA.

(OTOH,  SPHINX and .rst is so much worse than .Rmd....  OMG!)

**Comment by grburgess** [comment] 2020-08-12 06:51
I can do. I'll have to learn those formats as I usually go from Jupyter -> .rst / .md but I definitely want to help make this easier to get through in the future. In general, the docs are great, but understanding the MPI/threads part could use some tutorials. More soon.

**Comment by grburgess** [comment] 2020-08-12 06:52
> Yes,
> 
> so basically I just read that and it needs a bit more work from the user
> 
> Install MPI
> set-up `make/local`
> rebuilt cmdstan (e.g. should we have a different cmdstan folder for MPI)
> build executable
> --> mpirun -np N executable

Yes, this is what I was trying to do... but it doesn't work from CmdStanPy which makes sense now.

**Comment by ahartikainen** [comment] 2020-08-12 07:40
Ok, so "best-way" == "only way" ?

Adding extra step for sampling

    runset._cmds = [["mpirun", "-np", str(threads_per_chain)] + item for item in runset._cmds]

Do this before rest of the code

```
import cmdstanpy

import os

from concurrent.futures import ThreadPoolExecutor
from multiprocessing import cpu_count
from typing import Dict, List, Union

from cmdstanpy.cmdstan_args import (
    CmdStanArgs,
    SamplerArgs,
)
from cmdstanpy.stanfit import (
    RunSet,
    CmdStanMCMC,
)
from cmdstanpy.utils import MaybeDictToFilePath

def sample(
        self,
        data: Union[Dict, str] = None,
        chains: Union[int, None] = None,
        parallel_chains: Union[int, None] = None,
        threads_per_chain: Union[int, None] = None,
        seed: Union[int, List[int]] = None,
        chain_ids: Union[int, List[int]] = None,
        inits: Union[Dict, float, str, List[str]] = None,
        iter_warmup: int = None,
        iter_sampling: int = None,
        save_warmup: bool = False,
        thin: int = None,
        max_treedepth: float = None,
        metric: Union[str, List[str]] = None,
        step_size: Union[float, List[float]] = None,
        adapt_engaged: bool = True,
        adapt_delta: float = None,
        adapt_init_phase: int = None,
        adapt_metric_window: int = None,
        adapt_step_size: int = None,
        fixed_param: bool = False,
        output_dir: str = None,
        save_diagnostics: bool = False,
        show_progress: Union[bool, str] = False,
        validate_csv: bool = True,
    ) -> CmdStanMCMC:
        """
        Run or more chains of the NUTS sampler to produce a set of draws
        from the posterior distribution of a model conditioned on some data.
        This function validates the specified configuration, composes a call to
        the CmdStan ``sample`` method and spawns one subprocess per chain to run
        the sampler and waits for all chains to run to completion.
        Unspecified arguments are not included in the call to CmdStan, i.e.,
        those arguments will have CmdStan default values.
        For each chain, the ``CmdStanMCMC`` object records the command,
        the return code, the sampler output file paths, and the corresponding
        console outputs, if any. The output files are written either to a
        specified output directory or to a temporary directory which is deleted
        upon session exit.
        Output files are either written to a temporary directory or to the
        specified output directory.  Ouput filenames correspond to the template
        '<model_name>-<YYYYMMDDHHMM>-<chain_id>' plus the file suffix which is
        either '.csv' for the CmdStan output or '.txt' for
        the console messages, e.g. 'bernoulli-201912081451-1.csv'.
        Output files written to the temporary directory contain an additional
        8-character random string, e.g. 'bernoulli-201912081451-1-5nm6as7u.csv'.
        :param data: Values for all data variables in the model, specified
            either as a dictionary with entries matching the data variables,
            or as the path of a data file in JSON or Rdump format.
        :param chains: Number of sampler chains, must be a positive integer.
        :param parallel_chains: Number of processes to run in parallel. Must be
            a positive integer.  Defaults to ``multiprocessing.cpu_count()``.
        :param threads_per_chain: The number of threads to use in parallelized
            sections within an MCMC chain (e.g., when using the Stan functions
            ``reduce_sum()``  or ``map_rect()``).  This will only have an effect
            if the model was compiled with threading support. The total number
            of threads used will be ``parallel_chains * threads_per_chain``.
        :param seed: The seed for random number generator. Must be an integer
            between 0 and 2^32 - 1. If unspecified,
            ``numpy.random.RandomState()``
            is used to generate a seed which will be used for all chains.
            When the same seed is used across all chains,
            the chain-id is used to advance the RNG to avoid dependent samples.
        :param chain_ids: The offset for the random number generator, either
            an integer or a list of unique per-chain offsets.  If unspecified,
            chain ids are numbered sequentially starting from 1.
        :param inits: Specifies how the sampler initializes parameter values.
            Initialization is either uniform random on a range centered on 0,
            exactly 0, or a dictionary or file of initial values for some or all
            parameters in the model.  The default initialization behavior will
            initialize all parameter values on range [-2, 2] on the
            *unconstrained* support.  If the expected parameter values are
            too far from this range, this option may improve adaptation.
            The following value types are allowed:
            * Single number n > 0 - initialization range is [-n, n].
            * 0 - all parameters are initialized to 0.
            * dictionary - pairs parameter name : initial value.
            * string - pathname to a JSON or Rdump data file.
            * list of strings - per-chain pathname to data file.
        :param iter_warmup: Number of warmup iterations for each chain.
        :param iter_sampling: Number of draws from the posterior for each
            chain.
        :param save_warmup: When ``True``, sampler saves warmup draws as part of
            the Stan csv output file.
        :param thin: Period between saved samples.
        :param max_treedepth: Maximum depth of trees evaluated by NUTS sampler
            per iteration.
        :param metric: Specification of the mass matrix, either as a
            vector consisting of the diagonal elements of the covariance
            matrix ('diag' or 'diag_e') or the full covariance matrix
            ('dense' or 'dense_e').
            If the value of the metric argument is a string other than
            'diag', 'diag_e', 'dense', or 'dense_e', it must be
            a valid filepath to a JSON or Rdump file which contains an entry
            'inv_metric' whose value is either the diagonal vector or
            the full covariance matrix.
            If the value of the metric argument is a list of paths, its
            length must match the number of chains and all paths must be
            unique.
        :param step_size: Initial stepsize for HMC sampler.  The value is either
            a single number or a list of numbers which will be used as the
            global or per-chain initial step size, respectively.
            The length of the list of step sizes must match the number of
            chains.
        :param adapt_engaged: When True, adapt stepsize and metric.
        :param adapt_delta: Adaptation target Metropolis acceptance rate.
            The default value is 0.8.  Increasing this value, which must be
            strictly less than 1, causes adaptation to use smaller step sizes
            which improves the effective sample size, but may increase the time
            per iteration.
        :param adapt_init_phase: Iterations for initial phase of adaptation
            during which step size is adjusted so that the chain converges
            towards the typical set.
        :param adapt_metric_window: The second phase of adaptation tunes
            the metric and stepsize in a series of intervals.  This parameter
            specifies the number of iterations used for the first tuning
            interval; window size increases for each subsequent interval.
        :param adapt_step_size: Number of iterations given over to adjusting
            the step size given the tuned metric during the final phase of
            adaptation.
        :param fixed_param: When ``True``, call CmdStan with argument
            ``algorithm=fixed_param`` which runs the sampler without
            updating the Markov Chain, thus the values of all parameters and
            transformed parameters are constant across all draws and
            only those values in the generated quantities block that are
            produced by RNG functions may change.  This provides
            a way to use Stan programs to generate simulated data via the
            generated quantities block.  This option must be used when the
            parameters block is empty.  Default value is ``False``.
        :param output_dir: Name of the directory to which CmdStan output
            files are written. If unspecified, output files will be written
            to a temporary directory which is deleted upon session exit.
        :param save_diagnostics: Whether or not to save diagnostics. If True,
            csv output files are written to an output file with filename
            template '<model_name>-<YYYYMMDDHHMM>-diagnostic-<chain_id>',
            e.g. 'bernoulli-201912081451-diagnostic-1.csv'.
        :param show_progress: Use tqdm progress bar to show sampling progress.
            If show_progress=='notebook' use tqdm_notebook
            (needs nodejs for jupyter).
        :param validate_csv: If ``False``, skip scan of sample csv output file.
            When sample is large or disk i/o is slow, will speed up processing.
            Default is ``True`` - sample csv files are scanned for completeness
            and consistency.
        :return: CmdStanMCMC object
        """
        if chains is None:
            if fixed_param:
                chains = 1
            else:
                chains = 4
        if chains < 1:
            raise ValueError(
                'Chains must be a positive integer value, found {}.'.format(
                    chains
                )
            )
        if chain_ids is None:
            chain_ids = [x + 1 for x in range(chains)]
        else:
            if isinstance(chain_ids, int):
                if chain_ids < 1:
                    raise ValueError(
                        'Chain_id must be a positive integer value,'
                        ' found {}.'.format(chain_ids)
                    )
                chain_ids = [chain_ids + i for i in range(chains)]
            else:
                if not len(chain_ids) == chains:
                    raise ValueError(
                        'Chain_ids must correspond to number of chains'
                        ' specified {} chains, found {} chain_ids.'.format(
                            chains, len(chain_ids)
                        )
                    )
                for chain_id in chain_ids:
                    if chain_id < 0:
                        raise ValueError(
                            'Chain_id must be a non-negative integer value,'
                            ' found {}.'.format(chain_id)
                        )
        if parallel_chains is None:
            parallel_chains = max(min(cpu_count(), chains), 1)
        elif parallel_chains > chains:
            self._logger.info(
                'Requesting %u parallel_chains for %u chains,'
                ' running all chains in parallel.',
                parallel_chains,
                chains,
            )
            parallel_chains = chains
        elif parallel_chains < 1:
            raise ValueError(
                'Argument parallel_chains must be a positive integer value, '
                'found {}.'.format(parallel_chains)
            )
        if threads_per_chain is None:
            threads_per_chain = 1
        if threads_per_chain < 1:
            raise ValueError(
                'Argument threads_per_chain must be a positive integer value, '
                'found {}.'.format(threads_per_chain)
            )
        self._logger.debug(
            'total threads: %u', parallel_chains * threads_per_chain
        )
        os.environ['STAN_NUM_THREADS'] = str(threads_per_chain)

        refresh = None
        if show_progress:
            try:
                import tqdm

                self._logger.propagate = False
            except ImportError:
                self._logger.warning(
                    (
                        'Package tqdm not installed, cannot show progress '
                        'information. Please install tqdm with '
                        "'pip install tqdm'"
                    )
                )
                show_progress = False

        # TODO:  issue 49: inits can be initialization function

        sampler_args = SamplerArgs(
            iter_warmup=iter_warmup,
            iter_sampling=iter_sampling,
            save_warmup=save_warmup,
            thin=thin,
            max_treedepth=max_treedepth,
            metric=metric,
            step_size=step_size,
            adapt_engaged=adapt_engaged,
            adapt_delta=adapt_delta,
            adapt_init_phase=adapt_init_phase,
            adapt_metric_window=adapt_metric_window,
            adapt_step_size=adapt_step_size,
            fixed_param=fixed_param,
        )
        with MaybeDictToFilePath(data, inits) as (_data, _inits):
            args = CmdStanArgs(
                self._name,
                self._exe_file,
                chain_ids=chain_ids,
                data=_data,
                seed=seed,
                inits=_inits,
                output_dir=output_dir,
                save_diagnostics=save_diagnostics,
                method_args=sampler_args,
                refresh=refresh,
                logger=self._logger,
            )
            runset = RunSet(args=args, chains=chains, chain_ids=chain_ids)
            runset._cmds = [["mpirun", "-np", str(threads_per_chain)] + item for item in runset._cmds]
            pbar = None
            all_pbars = []

            with ThreadPoolExecutor(max_workers=parallel_chains) as executor:
                for i in range(chains):
                    if show_progress:
                        if (
                            isinstance(show_progress, str)
                            and show_progress.lower() == 'notebook'
                        ):
                            try:
                                tqdm_pbar = tqdm.tqdm_notebook
                            except ImportError:
                                msg = (
                                    'Cannot import tqdm.tqdm_notebook.\n'
                                    'Functionality is only supported on the '
                                    'Jupyter Notebook and compatible platforms'
                                    '.\nPlease follow the instructions in '
                                    'https://github.com/tqdm/tqdm/issues/394#'
                                    'issuecomment-384743637 and remember to '
                                    'stop & start your jupyter server.'
                                )
                                self._logger.warning(msg)
                                tqdm_pbar = tqdm.tqdm
                        else:
                            tqdm_pbar = tqdm.tqdm
                        # enable dynamic_ncols for advanced users
                        # currently hidden feature
                        dynamic_ncols = os.environ.get(
                            'TQDM_DYNAMIC_NCOLS', 'False'
                        )
                        if dynamic_ncols.lower() in ['0', 'false']:
                            dynamic_ncols = False
                        else:
                            dynamic_ncols = True

                        pbar = tqdm_pbar(
                            desc='Chain {} - warmup'.format(i + 1),
                            position=i,
                            total=1,  # Will set total from Stan's output
                            dynamic_ncols=dynamic_ncols,
                        )
                        all_pbars.append(pbar)
                    executor.submit(self._run_cmdstan, runset, i, pbar)

            # Closing all progress bars
            for pbar in all_pbars:
                pbar.close()
            if show_progress:
                # re-enable logger for console
                self._logger.propagate = True

            err_msg = 'Error during sampling.\n'
            if not runset._check_retcodes():
                for i in range(chains):
                    if runset._retcode(i) != 0:
                        err_msg = '{}chain {} returned error code {}\n'.format(
                            err_msg, i + 1, runset._retcode(i)
                        )
                console_errs = runset._get_err_msgs()
                if len(console_errs) > 0:
                    err_msg = '{}{}'.format(err_msg, ''.join(console_errs))
                raise RuntimeError(err_msg)

            mcmc = CmdStanMCMC(runset, validate_csv, logger=self._logger)
        return mcmc

from functools import partial
cmdstanpy.CmdStanModel.sample = partial(sample, model)
```

**Comment by mitzimorris** [comment] 2020-08-12 13:35
there should be a cleaner way to do the above - just my gut reaction

**Comment by ahartikainen** [comment] 2020-08-12 14:21
Currently probably only way.

If we want to support mpi, we should either support all the steps or keep it as a poweruser feature where user needs to setup "everything" and we just add that mpirun.

**Comment by mitzimorris** [comment] 2020-08-12 17:11
OK, understood - the key bit is which prefixes the call to the model executable with `mpirun`.
```
runset = RunSet(args=args, chains=chains, chain_ids=chain_ids)
runset._cmds = [["mpirun", "-np", str(threads_per_chain)] + item for item in runset._cmds]
```
then the command is run by the `_run_cmdstan` routine
via `executor.submit(self._run_cmdstan, runset, i, pbar)`

since `mpirun` is necessary for programs which use `map_rect`, we should support this because there are
situations where it's necessary to use `map_rect` instead of `reduce_sum`.

**Comment by mitzimorris** [comment] 2020-08-12 17:18
pinging @rok-cesnovar and @jgabry - what does CmdStanR do?

briefly considered trying to check whether or not the program actually uses `map_rect` or `reduce_sum` - I think there's too many edge cases there (use of includes) to bother checking the code - so will assume user knows what they're doing.

**Comment by mitzimorris** [comment] 2020-08-12 17:26
> I'll have to learn those formats as I usually go from Jupyter -> .rst / .md but I definitely want to help make this easier to get through in the future.

looks like this tool will translate from Jupyter to Rmd :  https://pypi.org/project/ipyrmd/

also, CmdStanPy repo has notebooks section:  https://github.com/stan-dev/cmdstanpy/tree/develop/docs/notebooks
you're welcome to contribute a notebook here

**Comment by jgabry** [comment] 2020-08-12 17:43
> pinging @rok-cesnovar and @jgabry - what does CmdStanR do w/r/t mpirun?

Right now nothing, but I think the plan is to eventually wrap up what @yizhang-yiz was able to do here

https://github.com/stan-dev/cmdstanr/issues/117#issuecomment-651382035

into a method. (Although that was with mpiexec. I don't know what the difference is between mpirun and mpiexec to be honest.)

**Comment by yizhang-yiz** [comment] 2020-08-12 17:46
> I don't know what the difference is between mpirun and mpiexec

Essentially none.

**Comment by grburgess** [comment] 2020-08-12 18:02
I think this essentially clears everything up for me

1) No MPI + reduce_sum atm (fine by me except over nodes but reduce_sum is super fast anyhow)
2) still not an easy way to use MPI + cmdstanpy (there is always an export to json and run cmdstan but it makes it a little harder to go right into arviz)
3) I will make some demo notebooks and some toy swatch scripts demonstrating some workflows to make it easier for people to jump right into HPC +cmdstanpy (few days -> weeks would also be nice to see how to combine single chain runs into one arviz InferenceData object... but I think I get how too do that with concat)

**Comment by ahartikainen** [comment] 2020-08-12 18:12
I think it is not too hard to set up small workflow with CmdStan + Python ThreadPool. You just need to be careful with paths (you could see what we do with CmdStanPy and copy the needed arguments)


There is `az.from_cmdstan` which reads CmdStan output (you can give it a list of csv files --> chains).

https://arviz-devs.github.io/arviz/generated/arviz.concat.html

To combine multiple objects together (with similar structure)

    idata = az.concat(idata1, idata2, dim="chain")

**Comment by grburgess** [comment] 2020-08-12 18:24
that's exactly where I was heading. 

The thread based is run is incredibly simple to do. With the new cmdstanpy, it is even more so.

**Comment by mitzimorris** [comment] 2021-03-19 16:58
closing - issue #360 is same issue, more straightforward solution

**Closed by mitzimorris** 2021-03-19 16:58 UTC
Labels: duplicate
