### ISSUE TITLE
Another code 70 run time error, string being passed as data, confusing error

### ISSUE THREAD

**Issue by breckbaldwin** [stan-dev/cmdstanpy#150] opened 2019-10-22 17:09 UTC
#### Summary:
Malformed data values will crash with inexplicable code 70 run time error, cmdstan has more sensible "variable: N, error: string values not allowed" for same problem.

#### Description:
```
import os
from cmdstanpy import cmdstan_path, CmdStanModel
import sys

model_code = """
data {
   int N;
}

parameters {
  real<lower=0,upper=1> theta;
} 
model {
   N ~ normal(theta,1);
}
"""

path='/tmp/foo.stan'

with open(path, 'w') as f:
  f.write(model_code)


hello_model = CmdStanModel(stan_file=path)
hello_model.compile()


json_data = {"N" : "1"} #bombs out with code 70 error

#json_data = {"N" : 1} #works

fit = hello_model.sample(data=json_data, csv_basename='./hello')


```
#### Additional Information:
Provide any additional information here.

#### Current Version:
cmdstanpy, 0.5.0, cmdstan 2.20.0 , OSX 10.13.6

**Comment by mitzimorris** [comment] 2019-10-24 14:11
duplicate of https://github.com/stan-dev/cmdstanpy/issues/141

**Closed by mitzimorris** 2019-10-24 14:11 UTC

**Comment by ahartikainen** [comment] 2019-10-24 14:22
We could check json data at input step, because it's always numerical.
