### ISSUE TITLE
Support for numpy arrays in data.

### ISSUE THREAD

**Issue by haganenoneko** [stan-dev/cmdstanpy#336] opened 2021-01-06 22:50 UTC
#### Summary:
Data for my model includes a 3d numpy array, but cmdstanpy raises an error when I start sampling. Below is the full error message:

`
Traceback (most recent call last):
  File "c:/...test_cmdstan.py", line 179, in <module>       **# call CmdStanModel.sample()**    
..................
  File "C:\...\AppData\Local\Programs\Python\Python37\lib\site-packages\cmdstanpy\model.py", line 687, in sample
    with MaybeDictToFilePath(data, inits) as (_data, _inits):
  File "C:\...\AppData\Local\Programs\Python\Python37\lib\site-packages\cmdstanpy\utils.py", line 929, in __init__
    jsondump(data_file, obj)
  File "C:\...\AppData\Local\Programs\Python\Python37\lib\site-packages\cmdstanpy\utils.py", line 330, in jsondump
    json.dump(data, fd)

TypeError:                1         2         3         4         5         6
0
0.0     0.990328  0.990328  0.990328  0.990328  0.990328  0.990328
40.0    0.989998  0.987736  0.977066  0.961163  0.939402  0.904460
80.0    0.989544  0.984597  0.958288  0.913079  0.855388  0.768979
120.0   0.989119  0.981505  0.939938  0.864234  0.772260  0.643681
160.0   0.988751  0.978566  0.922328  0.817665  0.696120  0.537366
...          ...       ...       ...       ...       ...       ...
3840.0  0.986853  0.934872  0.522510  0.087364  0.030524  0.026856
3880.0  0.986853  0.934865  0.522164  0.087215  0.030521  0.026856
3920.0  0.986853  0.934859  0.521831  0.087075  0.030518  0.026856
3960.0  0.986853  0.934853  0.521513  0.086943  0.030516  0.026856
4000.0  0.986853  0.934847  0.521208  0.086820  0.030513  0.026856

[101 rows x 6 columns] is not JSON serializable
`

#### Description:
I am able to run the Bernoulli example perfectly, and compilation of my own .stan models is working as well. It looks like cmdstanpy is trying to convert the input data into .json format, but I believe JSON files cannot handle numpy arrays. Ideally, I would like to preserve the 3d shape of my data, and would prefer not having to declare the data as a list of lists to make the JSON conversion happy, since I would later need to manipulate my Stan program accordingly. 

#### Additional Information:
I am running the latest version of cmdstanpy (cmdstan ver 2.25.0, cmdstanpy upgraded using pip) on a Windows 10 machine. For what it's worth, I have been able to compile and sample the same programs using the latest version of cmdstanr in R 4.0 without problems. 

Thank you!

**Comment by mitzimorris** [comment] 2021-01-06 23:47
> cmdstanpy is trying to convert the input data into .json format, but I believe JSON files cannot handle numpy arrays.

correct, JSON cannot handle numpy arrays - method `jsondump` converts numpy arrays to lists:  https://github.com/stan-dev/cmdstanpy/blob/18b285a2bf225a8780c908ea1c21ee4d9c0837fc/cmdstanpy/utils.py#L373-L375

looks like there aren't any unit tests for 3-d arrays.  will investigate.

**Comment by mitzimorris** [comment] 2021-01-07 00:58
the following test works as expected:

```
        arr = np.zeros(shape=(2, 3, 4))
        self.assertTrue(isinstance(arr, np.ndarray))
        self.assertEqual(arr.shape, (2,3,4))

        dict_3d_matrix = {'a': arr}
        file_3d_matrix = os.path.join(HERE, '3d_matrix.json')
        jsondump(file_3d_matrix, dict_3d_matrix)
```


resulting json file is OK:

```
cat test/3d_matrix.json 
{"a":[[[0.0,0.0,0.0,0.0],[0.0,0.0,0.0,0.0],[0.0,0.0,0.0,0.0]],[[0.0,0.0,0.0,0.0],[0.0,0.0,0.0,0.0],[0.0,0.0,0.0,0.0]]]}
```

and can be loaded via `jsonload`

**Comment by mitzimorris** [comment] 2021-01-07 01:11
your data is a Python dict, and one element of that dict is a 3d np.ndarray, correct?
perhaps this is a problem with the Windows JSON libs?    will test on a Windows 10 laptop later tonight.

**Comment by haganenoneko** [comment] 2021-01-07 02:51
> your data is a Python dict, and one element of that dict is a 3d np.ndarray, correct?
> perhaps this is a problem with the Windows JSON libs? will test on a Windows 10 laptop later tonight.

Yes, that's right.

**Comment by ahartikainen** [comment] 2021-01-07 05:03
I have not noticed any problems before on W10.

Can you tell what `type(arr)` and `arr.dtype` say?

**Comment by mitzimorris** [comment] 2021-02-04 15:37
cannot reproduce, closing this.

**Closed by mitzimorris** 2021-02-04 15:37 UTC
