### ISSUE TITLE
compiler option 'include-paths' not robust

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#520] opened 2022-01-25 04:41 UTC
#### Summary:

- The path to the include directory needs to be expanded to the absolute path because compilation happens in CMDSTAN_HOME dir, not current working directory.

- Update 'include_paths' to 'include-paths'.

#### Description:
Currently, user needs to do this:

```
include_dir = os.path.realpath(os.path.expanduser('include'))
pool_model = CmdStanModel(stan_file='pool.stan', stanc_options={'include_paths': [include_dir]})
```

It should be done by the CmdStanModel class or delegated to the CompilerOpts class.

Stanc3 compiler gives warning about 'include_paths' being deprecated.

Also investigate why logging with DEBUG during compilation gives this result:

```
DEBUG:cmdstanpy:Command ['./bin/stanc', '--info', '/Users/mitzi/github/stan-dev/example-models/jupyter/partial-pool-binary-trials/pool.stan']
	error during processing Operation not permitted
```

**Comment by WardBrian** [comment] 2022-01-25 13:04
I think the debug issue is a duplicate of #516, and includd_paths was changed to include-paths as part of that fix

my guess is this also causes problems when the temporary copied file is used?

**Comment by WardBrian** [comment] 2022-01-25 14:42
We should add that logic here I believe

https://github.com/stan-dev/cmdstanpy/blob/a40b6a185163299f37d9d503fd3b10c33330304e/cmdstanpy/compiler_opts.py#L171-L172

I should note in this specific example, the user may consider changing their stan code to be `#include includes/foo.stan` rather than `#include foo.stan`, since then the fact that we add the stan file's directory by default makes fussing with the include paths not required

**Comment by mitzimorris** [comment] 2022-01-25 17:59
> the user may consider changing their stan code to be #include includes/foo.stan rather than #include foo.stan

doh!  so much cleaner!

**Closed** 2022-01-27 17:56 UTC
Labels: code cleanup, method compilation
